package org.turtledev.richard.ui

object Strings {
    private val de = mapOf(
        "welcome" to "Willkommen",
        "login_to" to "Melde dich bei RICHARD an",
        "username" to "Benutzername",
        "password" to "Passwort",
        "login" to "ANMELDEN",
        "no_account" to "Noch kein Konto? Registrieren",
        "register" to "Registrieren",
        "register_title" to "Konto erstellen",
        "register_sub" to "Tritt der RICHARD-Community bei",
        "already_account" to "Bereits ein Konto? Login",
        "setup_title" to "Messenger Setup",
        "server_addr" to "Server Adresse",
        "connect" to "JETZT VERBINDEN",
        "next" to "WEITER",
        "choose_lang" to "Wähle deine Sprache",
        "online" to "Online",
        "message_hint" to "Nachricht...",
        "settings" to "Einstellungen",
        "logout" to "Abmelden",
        "profile" to "Profil & Account",
        "save" to "PROFIL AKTUALISIEREN",
        "delete_account" to "KONTO LÖSCHEN",
        "server_ip_change" to "Server IP ändern",
        "fill_all" to "Bitte alle Felder ausfüllen.",
        "new_password" to "Neues Passwort",
        "password_hint" to "Leer lassen für keine Änderung",
        "danger_zone" to "Gefahrenzone",
        "danger_desc" to "Diese Aktionen können nicht rückgängig gemacht werden.",
        "delete_confirm_title" to "Konto wirklich löschen?",
        "delete_confirm_text" to "Alle deine Daten und Nachrichten werden unwiderruflich gelöscht. Du wirst zum Setup-Screen zurückgeleitet.",
        "logout_confirm_text" to "Möchtest du dich wirklich ausloggen?",
        "cancel" to "ABBRECHEN",
        "delete" to "LÖSCHEN",
        "admin_info" to "Admin-Daten können aus Sicherheitsgründen nicht über die App geändert werden.",
        "back" to "Zurück",
        "about" to "Über RICHARD",
        "about_desc" to "Richard ist ein lokaler messanger.",
        "version" to "Version 3.1 canary",
        "appearance" to "Erscheinungsbild",
        "theme" to "Design",
        "theme_system" to "Systemstandard",
        "theme_light" to "Hell",
        "theme_dark" to "Dunkel",
        "primary_color" to "Primärfarbe",
        "confirm_password" to "Passwort bestätigen",
        "passwords_mismatch" to "Passwörter stimmen nicht überein.",
        "enter_to_send" to "Enter-Taste sendet Nachricht",
        "chat_font_size" to "Chat Schriftgröße",
        "font_size_small" to "Klein",
        "font_size_medium" to "Mittel",
        "font_size_large" to "Groß"
    )

    private val en = mapOf(
        "welcome" to "Welcome",
        "login_to" to "Sign in to RICHARD",
        "username" to "Username",
        "password" to "Password",
        "login" to "LOGIN",
        "no_account" to "No account? Register",
        "register" to "Register",
        "register_title" to "Create account",
        "register_sub" to "Join the RICHARD community",
        "already_account" to "Already have an account? Login",
        "setup_title" to "Messenger Setup",
        "server_addr" to "Server Address",
        "connect" to "CONNECT NOW",
        "next" to "NEXT",
        "choose_lang" to "Choose your language",
        "online" to "Online",
        "message_hint" to "Message...",
        "settings" to "Settings",
        "logout" to "Logout",
        "profile" to "Profile & Account",
        "save" to "UPDATE PROFILE",
        "delete_account" to "DELETE ACCOUNT",
        "server_ip_change" to "Change server IP",
        "fill_all" to "Please fill all fields.",
        "new_password" to "New Password",
        "password_hint" to "Leave empty for no change",
        "danger_zone" to "Danger Zone",
        "danger_desc" to "These actions cannot be undone.",
        "delete_confirm_title" to "Delete account?",
        "delete_confirm_text" to "All your data and messages will be permanently deleted. You will be redirected to setup.",
        "logout_confirm_text" to "Do you really want to log out?",
        "cancel" to "CANCEL",
        "delete" to "DELETE",
        "admin_info" to "Admin data cannot be changed via the app for security reasons.",
        "back" to "Back",
        "about" to "About RICHARD",
        "about_desc" to "Richard is a local messenger.",
        "version" to "Version 3.1 canary",
        "appearance" to "Appearance",
        "theme" to "Theme",
        "theme_system" to "System default",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "primary_color" to "Primary Color",
        "confirm_password" to "Confirm Password",
        "passwords_mismatch" to "Passwords do not match.",
        "enter_to_send" to "Enter key sends message",
        "chat_font_size" to "Chat Font Size",
        "font_size_small" to "Small",
        "font_size_medium" to "Medium",
        "font_size_large" to "Large"
    )

    private val fr = mapOf(
        "welcome" to "Bienvenue",
        "login_to" to "Connectez-vous à RICHARD",
        "username" to "Nom d'utilisateur",
        "password" to "Mot de passe",
        "login" to "CONNEXION",
        "no_account" to "Pas de compte ? S'inscrire",
        "register" to "S'inscrire",
        "register_title" to "Créer un compte",
        "register_sub" to "Rejoignez la communauté RICHARD",
        "already_account" to "Déjà un compte ? Connexion",
        "setup_title" to "Configuration",
        "server_addr" to "Adresse du serveur",
        "connect" to "CONNECTER",
        "next" to "SUIVANT",
        "choose_lang" to "Choisissez votre langue",
        "online" to "En ligne",
        "message_hint" to "Message...",
        "settings" to "Paramètres",
        "logout" to "Déconnexion",
        "profile" to "Profil & Compte",
        "save" to "METTRE À JOUR LE PROFIL",
        "delete_account" to "SUPPRIMER LE COMPTE",
        "server_ip_change" to "Changer l'IP du serveur",
        "fill_all" to "Veuillez remplir tous les champs.",
        "new_password" to "Nouveau mot de passe",
        "password_hint" to "Laisser vide pour aucun changement",
        "danger_zone" to "Zone de danger",
        "danger_desc" to "Ces actions ne peuvent pas être annulées.",
        "delete_confirm_title" to "Supprimer le compte ?",
        "delete_confirm_text" to "Toutes vos données et messages seront supprimés définitivement. Vous serez redirigé vers la configuration.",
        "logout_confirm_text" to "Voulez-vous vraiment vous déconnecter ?",
        "cancel" to "ANNULER",
        "delete" to "SUPPRIMER",
        "admin_info" to "Les données d'administration ne peuvent pas être modifiées via l'application pour des raisons de sécurité.",
        "back" to "Retour",
        "about" to "À propos de RICHARD",
        "about_desc" to "Richard est un messager local.",
        "version" to "Version 3.1 canary",
        "appearance" to "Apparence",
        "theme" to "Thème",
        "theme_system" to "Système par défaut",
        "theme_light" to "Clair",
        "theme_dark" to "Sombre",
        "primary_color" to "Couleur primaire",
        "confirm_password" to "Confirmer le mot de passe",
        "passwords_mismatch" to "Les mots de passe ne correspondent pas.",
        "enter_to_send" to "La touche Entrée envoie le message",
        "chat_font_size" to "Taille de police du chat",
        "font_size_small" to "Petite",
        "font_size_medium" to "Moyenne",
        "font_size_large" to "Grande"
    )

    private val es = mapOf(
        "welcome" to "Bienvenido",
        "login_to" to "Inicia sesión en RICHARD",
        "username" to "Nombre de usuario",
        "password" to "Contraseña",
        "login" to "INICIAR SESIÓN",
        "no_account" to "¿No tienes cuenta? Regístrate",
        "register" to "Registrarse",
        "register_title" to "Crear cuenta",
        "register_sub" to "Únete a la comunidad RICHARD",
        "already_account" to "¿Ya tienes cuenta? Iniciar sesión",
        "setup_title" to "Configuración",
        "server_addr" to "Dirección del servidor",
        "connect" to "CONECTAR AHORA",
        "next" to "SIGUIENTE",
        "choose_lang" to "Elige tu idioma",
        "online" to "En línea",
        "message_hint" to "Mensaje...",
        "settings" to "Ajustes",
        "logout" to "Cerrar sesión",
        "profile" to "Perfil y cuenta",
        "save" to "ACTUALIZAR PERFIL",
        "delete_account" to "ELIMINAR CUENTA",
        "server_ip_change" to "Cambiar IP del servidor",
        "fill_all" to "Por favor complete todos los campos.",
        "new_password" to "Nueva contraseña",
        "password_hint" to "Dejar vacío para no cambiar",
        "danger_zone" to "Zona de peligro",
        "danger_desc" to "Estas acciones no se pueden deshacer.",
        "delete_confirm_title" to "¿Eliminar cuenta?",
        "delete_confirm_text" to "Todos tus datos y mensajes se eliminarán permanentemente. Serás redirigido a la configuración.",
        "logout_confirm_text" to "¿Realmente quieres cerrar sesión?",
        "cancel" to "CANCELAR",
        "delete" to "ELIMINAR",
        "admin_info" to "Los datos de administrador no se pueden cambiar a través de la aplicación por razones de seguridad.",
        "back" to "Atrás",
        "about" to "Acerca de RICHARD",
        "about_desc" to "Richard es un mensajero local.",
        "version" to "Version 3.1 canary",
        "appearance" to "Apariencia",
        "theme" to "Tema",
        "theme_system" to "Predeterminado del sistema",
        "theme_light" to "Claro",
        "theme_dark" to "Oscuro",
        "primary_color" to "Color primario",
        "confirm_password" to "Confirmar contraseña",
        "passwords_mismatch" to "Las contraseñas no coinciden.",
        "enter_to_send" to "La tecla Enter envía el mensaje",
        "chat_font_size" to "Tamaño de fuente del chat",
        "font_size_small" to "Pequeño",
        "font_size_medium" to "Mediano",
        "font_size_large" to "Grande"
    )

    private val it = mapOf(
        "welcome" to "Benvenuto",
        "login_to" to "Accedi a RICHARD",
        "username" to "Nome utente",
        "password" to "Password",
        "login" to "ACCEDI",
        "no_account" to "Non hai un account? Registrati",
        "register" to "Registrati",
        "register_title" to "Crea account",
        "register_sub" to "Unisciti alla comunità RICHARD",
        "already_account" to "Hai già un account? Accedi",
        "setup_title" to "Configurazione",
        "server_addr" to "Indirizzo del server",
        "connect" to "CONNETTITI ORA",
        "next" to "AVANTI",
        "choose_lang" to "Scegli la tua lingua",
        "online" to "Online",
        "message_hint" to "Messaggio...",
        "settings" to "Impostazioni",
        "logout" to "Disconnetti",
        "profile" to "Profilo e account",
        "save" to "AGGIORNA PROFILO",
        "delete_account" to "ELIMINA ACCOUNT",
        "server_ip_change" to "Cambia IP del server",
        "fill_all" to "Si prega di compilare tutti i campi.",
        "new_password" to "Nuova password",
        "password_hint" to "Lascia vuoto per non modificare",
        "danger_zone" to "Zona di pericolo",
        "danger_desc" to "Queste azioni non possono essere annullate.",
        "delete_confirm_title" to "Elimina account?",
        "delete_confirm_text" to "Tutti i tuoi dati e messaggi verranno eliminati definitivamente. Sarai reindirizzato alla configurazione.",
        "logout_confirm_text" to "Vuoi davvero uscire?",
        "cancel" to "ANNULLA",
        "delete" to "ELIMINA",
        "admin_info" to "I dati dell'amministratore non possono essere modificati tramite l'app per motivi di sicurezza.",
        "back" to "Indietro",
        "about" to "Informazioni su RICHARD",
        "about_desc" to "Richard è un messenger locale.",
        "version" to "Version 3.1 canary",
        "appearance" to "Aspetto",
        "theme" to "Tema",
        "theme_system" to "Predefinito di sistema",
        "theme_light" to "Chiaro",
        "theme_dark" to "Scuro",
        "primary_color" to "Colore primario",
        "confirm_password" to "Conferma password",
        "passwords_mismatch" to "Le password non corrispondono.",
        "enter_to_send" to "Il tasto Invio invia il messaggio",
        "chat_font_size" to "Dimensione carattere chat",
        "font_size_small" to "Piccolo",
        "font_size_medium" to "Medio",
        "font_size_large" to "Grande"
    )

    private val tr = mapOf(
        "welcome" to "Hoş geldiniz",
        "login_to" to "RICHARD'a giriş yap",
        "username" to "Kullanıcı adı",
        "password" to "Şifre",
        "login" to "GİRİŞ YAP",
        "no_account" to "Hesabınız yok mu? Kayıt ol",
        "register" to "Kayıt ol",
        "register_title" to "Hesap oluştur",
        "register_sub" to "RICHARD topluluğuna katıl",
        "already_account" to "Zaten hesabınız var mı? Giriş yap",
        "setup_title" to "Kurulum",
        "server_addr" to "Sunucu Adresi",
        "connect" to "ŞİMDİ BAĞLAN",
        "next" to "İLERİ",
        "choose_lang" to "Dilinizi seçin",
        "online" to "Çevrimiçi",
        "message_hint" to "Mesaj...",
        "settings" to "Ayarlar",
        "logout" to "Çıkış yap",
        "profile" to "Profil ve Hesap",
        "save" to "PROFİLİ GÜNCELLE",
        "delete_account" to "HESABI SİL",
        "server_ip_change" to "Sunucu IP'sini değiştir",
        "fill_all" to "Lütfen tüm alanları doldurun.",
        "new_password" to "Yeni şifre",
        "password_hint" to "Değişiklik yapmamak için boş bırakın",
        "danger_zone" to "Tehlikeli Bölge",
        "danger_desc" to "Bu işlemler geri alınamaz.",
        "delete_confirm_title" to "Hesabı sil?",
        "delete_confirm_text" to "Tüm verileriniz ve mesajlarınız kalıcı olarak silinecektir. Kuruluma yönlendirileceksiniz.",
        "logout_confirm_text" to "Gerçekten çıkış yapmak istiyor musunuz?",
        "cancel" to "İPTAL",
        "delete" to "SİL",
        "admin_info" to "Yönetici verileri güvenlik nedeniyle uygulama üzerinden değiştirilemez.",
        "back" to "Geri",
        "about" to "RICHARD Hakkında",
        "about_desc" to "Richard yerel bir mesajlaşma aracıdır.",
        "version" to "Versiyon 3.1 canary",
        "appearance" to "Görünüm",
        "theme" to "Tema",
        "theme_system" to "Sistem varsayılanı",
        "theme_light" to "Açık",
        "theme_dark" to "Koyu",
        "primary_color" to "Ana Renk",
        "confirm_password" to "Şifreyi onayla",
        "passwords_mismatch" to "Şifreler eşleşmiyor.",
        "enter_to_send" to "Enter tuşu mesaj gönderir",
        "chat_font_size" to "Sohbet Yazı Tipi Boyutu",
        "font_size_small" to "Küçük",
        "font_size_medium" to "Orta",
        "font_size_large" to "Büyük"
    )

    fun get(key: String, lang: String): String {
        val bundle = when(lang) {
            "en" -> en
            "fr" -> fr
            "es" -> es
            "it" -> it
            "tr" -> tr
            else -> de
        }
        return bundle[key] ?: key
    }
}
